<?php
$theme = config('theme', 'main');
$color = config($theme.'-colored', '#ff5533');
?>

<div style="position:relative;">

    <form enctype="multipart/form-data" action="<?php echo getFullUrl(true)?>" method="post" class="general-form">
        <?php if(model('user')->isAdmin()):?>
            <input type="hidden" name="val[userid]" value="<?php echo $C->request->input('id')?>"/>
        <?php endif?>
        <div class="inner-container" style="padding-top: 80px;">

            <div id="video-form-container" >
                <div class="row mt-4">
                    <div class="col-md-10">

                        <div class="form-group">
                            <label><?php _l('radio::stream-link')?></label>
                            <div class="row mt-2">

                                <div class="col-sm-4">
                                    <select class="form-control" name="val[link_type]">
                                        <option <?php echo ($radio and $radio['link_type'] == 'icecast') ? 'selected' : null?>  value="icecast">Icecast</option>
                                        <option <?php echo ($radio and $radio['link_type'] == 'shoutcast') ? 'selected' : null?> value="shoutcast">Shoutcast</option>
                                        <option <?php echo ($radio and $radio['link_type'] == 'other') ? 'selected' : null?> value="other"><?php _l('other')?></option>
                                    </select>
                                </div>
                                <div class="col-sm-8">
                                    <input type="text" value="<?php echo ($radio) ? $radio['link'] : null?>" placeholder="<?php _l('radio::stream-link')?>" class="form-control" name="val[link]"/>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label><?php _l('title')?></label>
                            <input type="text" name="val[title]"  value="<?php echo ($radio) ? $radio['title'] : null?>"  class="form-control "/>
                        </div>

                        <div class="form-group">
                            <label><?php _l('description')?></label>
                            <textarea name="val[description]"  rows="5" class="form-control "><?php echo ($radio) ? $radio['description'] : null?></textarea>
                        </div>



                        <div class="form-group ">
                            <label><?php _l('genre')?></label>
                            <select data-ui-select="true" class=" select-input" name="val[genre]">
                                <?php foreach ($C->model('admin')->getGenres() as $genre):?>
                                    <option <?php echo ($radio and $radio['genre'] == $genre['id']) ? 'selected' : null?> value="<?php echo $genre['id']?>"><?php echo $genre['name']?></option>
                                <?php endforeach;?>
                            </select>
                        </div>



                        <div class="form-group">
                            <label><?php _l('tags')?></label>
                            <input autocomplete="off" value="<?php echo ($radio) ? $radio['tags'] : null?>" type="text" name="val[tags]" class=" input-tags video-tags" >
                        </div>



                    </div>

                    <div class="col-md-2">
                        <div class="avatar-placeholder mt-4" style="width: 100%;height:170px;border-style:dashed">
                            <div id="songAvatar" style="background-image: url(<?php echo ($radio) ? model('radio::radio')->getArt($radio, 600) : null;?>);display: block;"></div>
                            <i class="la la-photo"></i>
                        </div>

                        <div class="input-picker mb-3">
                            <button class="btn btn-secondary btn-sm btn-block round-sm"><?php _l('select-image')?></button>
                            <input id="songAvatar-input"  data-placeholder="#songAvatar" onchange="validate_file_size(this, 'image')" type="file" name="img"/>
                        </div>

                    </div>
                </div>

                <hr/>
                <div class="progress mt-1 hide" id="trackUploadProgress" style="margin: 7px 0; height:2px;">
                    <div class="progress-bar" role="progressbar" style="width: 0%;background:#FF533E;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <button data-size="s" data-style="zoom-in" id="upload-submit" class="btn btn-primary round-sm ladda-button" type="submit"><?php _l('publish')?></button>
                <?php if($radio):?>
                    <a class="btn btn-danger round-sm float-right confirm"  href="<?php echo url('radio/edit', array('id' => $radio['id'], 'action' => 'delete'))?>"><?php _l('delete')?></a>
                <?php endif?>
            </div>

        </div>


    </form>
</div>