<script>
    function adsBannerDeduct(id) {
        $.ajax({
            url: buildLink('ads/clicking', [{key: 'id', value: id}])
        });
    }
</script>
<?php $ad = model('advert::advert')->display('image','banner');?>
<?php if($ad):?>
    <h5 class="clearfix"> <a href="<?php echo url('advertising')?>" data-ajax="true" class="float-right" style="font-size: 12px;position:relative;top:5px"><?php _l('advert::create-ads')?></a> </h5>
    <a <?php echo ($ad['pay_type'] == 1) ? "onclick='adsBannerDeduct(".$ad['id'].")'":null?> target="_blank" class="side-card mb-3"  href="<?php echo $ad['ad_link']?>">
        <div class="image"  style="background-image: url(<?php echo url_img($ad['ad_image'], 920);?>);height:100px"></div>
    </a>
<?php endif?>

